### ISSUE TITLE
Refining how Waku's importance is presented

### ISSUE THREAD

**Issue by LordGhostX** [waku-org/docs.waku.org#57]
## Background

Our validation of Waku's importance heavily relies on comparisons with Whisper: https://github.com/waku-org/waku.guide/pull/53#discussion_r1208764926.

## Challenge

Since there is no alternative to Waku or a replacement for Whisper, many readers will likely need help understanding the Whisper context. Hence, we must develop a more engaging and modern approach to effectively communicate Waku's importance to guarantee clarity and understanding for all audiences.

cc: @fryorcraken @hackyguru

**Comment by fryorcraken** [comment]
I think what we are aiming to do on the website is a good approach: Modern context presentation first, followed by historical context.

This then might not be needed in the docs if it's already in the website. Or maybe just copied from website to docs so that someone who reads the dosc but did not check the website can still get the info.

Let's see how the website turns out first.
