### ISSUE TITLE
Structure of Navigation items 

### ISSUE THREAD

**Issue by amirhouieh** [waku-org/docs.waku.org#72]
@fryorcraken 
I've been checking out the side nav bar and noticed something. The `/presentations` & `/guides/Nodes&...` links are pointed to pages on wak.org, right?

So, two quick questions:
1. Why are they flagged as external links? They've got the outward arrow icon and all.
2. Do we need these in the side bar? They're their own standalone folders.

Just a thought - maybe we could pop these folders ('docs', 'guides', 'presentations') into the header navbar instead of having them hang out in the side bar. Might make things a bit clearer for folks using the site.

What do you think?

**Comment by LordGhostX** [comment]
Hi @amirhouieh,

1. We labeled them as external links because they lead to different documentation sections. Clicking on these links redirects users to another part of the documentation with another sidebar. The inclusion of the arrow icon and the opening of a new tab serve as indications of this behavior.
2. We don't need them in the sidebar, but they'll be helpful for new users. For instance, when users seek information on running a Waku node, they quickly notice the "Nodes and SDKs" in the sidebar before the dropdown in the "Guides" navbar and footer.
3. We already have the "Nodes and SDKs" in the "Guides" navbar dropdown and "Watch Our Presentations" in the "Community" dropdown. Adding them again is a duplicate.

More:

* In a recent usability test with @SionoiS, I provided the docs link for the first time and asked for his actions if he needed information on running a Waku node. He promptly clicked "Nodes and SDKs" in the sidebar, scrolled to the node section, and selected the "Run a Nwaku Node" guide.
* The "Presentations" link offers video resources for new users who prefer that format. Nevertheless, I am open to removing it from the sidebar.
